platform:
  - x86
  - x64

environment:
  CONDA_RECIPE: conda
  CONDA_VERSION: 3
      
  matrix:
    - CONDA_PY: 37
    - CONDA_PY: 38
      CONDA_NPY: 116

install:
  - git clone https://github.com/openalea/appveyor-ci.git
  - cd appveyor-ci
  - call install.bat
  - conda config --prepend channels conda-forge
  - conda install -y conda-verify

before_build:
  - call before_build.bat

build_script:
  - call build_script.bat

after_build:
  - call after_build.bat

deploy:
  provider: Script

before_deploy:
  - call before_deploy.bat

deploy_script:
  - call deploy_script.bat

after_deploy:
  - call after_deploy.bat

on_success:
  - call on_success.bat

on_failure:
  - call on_failure.bat

on_finish:
  - call on_finish.bat
