# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: continuumio/miniconda:latest

stages:
 - build

deploy_phenomenal_on_linux:
 stage: build

 script:
   - apt-get update
   - apt-get -y install freeglut3-dev gcc g++

   - echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
   - source ~/.bashrc

   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - conda install conda-build
   - conda install conda-verify

   - pwd

   - cd conda
   - conda build -c openalea -c conda-forge .
   - cd ..

   - conda create -n deploy -c openalea -c conda-forge --use-local python=2.7 openalea.phenomenal
   - conda activate deploy
   - conda install -c openalea -c conda-forge opencv
   - conda install -c openalea -c conda-forge coverage

   - conda info -e
   - conda list

   - cd test
   - nosetests --with-coverage --cover-erase --cover-html --cover-package=openalea.phenomenal --cover-tests --cover-inclusive
   - conda deactivate

 artifacts:
  paths:
   - cover/