# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: continuumio/miniconda:latest

stages:
 - build
 - deploy

before_script:
   - echo "Before script section"
   - echo "For example you might run an update here or install a build dependency"
   - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

install:
 stage: build

 script:
   - apt-get update
   - apt-get -y install freeglut3-dev

   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - conda install conda-build
   - conda create --name phenome python
   - source activate phenome
   - pwd
   - cd ./build_tools/conda
   - conda build -c conda-forge -c openalea .
   - cd ../..

   - conda install -c conda-forge -c openalea --use-local openalea.phenomenal
   - conda install -c conda-forge notebook nose sphinx sphinx_rtd_theme pandoc

   - conda info -e
   - conda list

   - nosetests test --with-coverage --cover-erase --cover-html --cover-package=openalea.phenomenal --cover-tests --cover-inclusive
   - source deactivate

 artifacts:
  paths:
   - cover/

pages:
  stage: deploy
  dependencies:
    - install
  script:
    - mv cover/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master