# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: continuumio/miniconda:latest

before_script:
   - echo "Before script section"
   - echo "For example you might run an update here or install a build dependency"
   - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build_conda_phenome_env:
 stage: build
 cache:
  paths:
   - /
 script:
   - conda create --name phenome python --yes
   - source activate phenome
   - echo "Dependency"
   - conda install numpy --yes
   - conda install opencv --yes
   - conda install scipy --yes
   - conda install scikit-learn --yes
   - conda install networkx --yes
   - conda install vtk --yes
   - echo "Optional dependency"
   - conda install jupyter --yes
   - conda install nose --yes
   - conda install coverage --yes
   - conda install matplotlib --yes

   - python setup.py develop --prefix=$CONDA_PREFIX
   - source deactivate

test_phenome:
 stage: test
 cache:
  paths:
   - /
 script:
   - conda info --envs
   - source activate phenome
   - nosetests test
   - source deactivate

deploy_1:
 stage: deploy
 script:
   - echo "Do your deploy here"