# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: continuumio/miniconda:latest

stages:
 - build

deploy_phenomenal_on_linux:
 stage: build

 script:
   - apt-get update
   - apt-get -y install freeglut3-dev
   - apt-get -y install gcc
   - apt-get -y install g++

   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - conda install conda-build

   - pwd

   - cd conda
   - conda build -c conda-forge -c openalea .
   - cd ..

   - conda create -n deploy -c openalea -c conda-forge --use-local python=2.7 openalea.phenomenal
   - source activate deploy

   - conda install -c openalea -c conda-forge notebook sphinx sphinx_rtd_theme pandoc coverage ipyvolume nbconvert

   - conda info -e
   - conda list

   - nosetests test --with-coverage --cover-erase --cover-html --cover-package=openalea.phenomenal --cover-tests --cover-inclusive
   - source deactivate


 artifacts:
  paths:
   - cover/