name: phenome
channels:
  - conda-forge
  - openalea
  - defaults
dependencies:
  - numba
  - python
  - setuptools
  - openalea.deploy
  - openalea.core
  - numpy
  - scikit-learn
  - scikit-image
  - scipy
  - matplotlib
  - networkx
  - vtk
  - opencv
  - nose
  - notebook
  - sphinx
  - sphinx_rtd_theme
  - pandoc
  - ipyvolume
  - pywin32 [win]
