{% set pyproject = load_file_data('pyproject.toml') %}
{% set description = pyproject.get('project').get('description') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}


package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ GIT_DESCRIBE_TAG | replace("v", "") }}

source:
  path: ..

build:
  script: 
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python

  build:
    - {{ compiler('c') }} 
    - {{ compiler("cxx") }}

  run:
    - python x.x
    - numpy x.x
    - cython
    - numba
    - scipy
    - scikit-image
    - scikit-learn
    - networkx
    - opencv [win or linux]
    - opencv >4.1.2 [osx]
    - matplotlib
    - vtk
    - skan
    - pywin32 [win]

test:
  imports:
    - openalea.phenomenal
    - openalea.phenomenal.calibration
    - openalea.phenomenal.data
    - openalea.phenomenal.display
    - openalea.phenomenal.image
    - openalea.phenomenal.mesh
    - openalea.phenomenal.multi_view_reconstruction
    - openalea.phenomenal.object
    - openalea.phenomenal.segmentation
    - openalea.phenomenal.tracking
  requires:
    - pytest
  source_files:
    - doc/examples/data/**
    - test/data/**
    - test/test_calibration/**
    - test/test_image/**
    - test/test_mesh/**
    - test/test_multi_view_reconstruction/**
    - test/test_object/**
    - test/test_tracking/**
    - test/test_segmentation/**
  commands:
    - pytest

about:
  home: {{ home }}
  summary: {{ description }}
  license: Cecill-C License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - artzet-s
    - pradal
