{% set data = load_setup_py_data() %}

package:
  name: openalea.phenomenal
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  string: phenomenal
  script:
    - {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
    

  host:
    - python
    - setuptools
    - cython    
    - numpy
    - scipy

  run:
    - python
    - numpy
    - cython
    - numba
    - scipy
    - scikit-image
    - scikit-learn
    - networkx
    - opencv [win or linux]
    - opencv!=4.1.2 [osx]
    - matplotlib
    - vtk
    - skan=0.10
    - pywin32 [win]

test:
  imports:
    - openalea.phenomenal
    - openalea.phenomenal.calibration
    - openalea.phenomenal.data
    - openalea.phenomenal.display
    - openalea.phenomenal.image
    - openalea.phenomenal.mesh
    - openalea.phenomenal.multi_view_reconstruction
    - openalea.phenomenal.object
    - openalea.phenomenal.segmentation
    - openalea.phenomenal.tracking
  requires:
    - pytest
  source_files:
    - examples/data/**
    - test/data/**
    - test/test_calibration/**
    - test/test_image/**
    - test/test_mesh/**
    - test/test_multi_view_reconstruction/**
    - test/test_object/**
    - test/test_tracking/**
    - test/test_segmentation/**
  commands:
    - pytest

about:
  home: {{ data.get('url') }}
  license: Cecill-C License
  license_file: LICENSE.txt
  summary: {{ data.get('description') }}

extra:
  recipe-maintainers:
    - artzet-s
    - pradal
