package:
  name: openalea.phenomenal
  version: "1.9.2"

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  string: phenomenal
  script: {{PYTHON}} setup.py install

requirements:
  host:
    - python x.x
    - numpy x.x
    - scipy x.x

  build:
    - {{ compiler('c') }} 
    - {{ compiler("cxx") }} 
    - python
    - setuptools
    - numpy
    - cython


  run:
    - python x.x
    - numpy x.x
    - numba
    - scipy x.x
    - scikit-image
    - scikit-learn
    - networkx
    - opencv [win or linux]
    - opencv!=4.1.2 [osx]
    - matplotlib
    - vtk
    - skan=0.10
    - pywin32 [win]

test:
  imports:
    - openalea.phenomenal
    - openalea.phenomenal.calibration
    - openalea.phenomenal.data
    - openalea.phenomenal.display
    - openalea.phenomenal.image
    - openalea.phenomenal.mesh
    - openalea.phenomenal.multi_view_reconstruction
    - openalea.phenomenal.object
    - openalea.phenomenal.segmentation
    - openalea.phenomenal.tracking
  requires:
    - pytest
  source_files:
    - examples/data/**
    - test/data/**
    - test/test_calibration/**
    - test/test_image/**
    - test/test_mesh/**
    - test/test_multi_view_reconstruction/**
    - test/test_object/**
    - test/test_tracking/**
    - test/test_segmentation/**
  commands:
    - pytest

about:
  home: https://github.com/openalea/phenomenal
  license: Cecill-C License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - artzet-s
    - pradal
