package:
  name: openalea.phenomenal
  version: "1.7.0b0"

source:
  path: ..

build:
  features:
    - vc9               [win and py27]
    - vc14              [win and py36]
  track_features:
    - vc9               [win and py27]
    - vc14              [win and py36]
  number: 0
  preserve_egg_dir: True
  string: phenomenal
  script:
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - vs2008_runtime    [win and py27]
    - vs2015_runtime    [win and py36]
    - libgcc-ng [linux]
    - pywin32 [win]
    - numpy

  run:
    - python
    - numpy
    - numba
    - cython
    - scipy
    - scikit-image
    - scikit-learn
    - networkx=2.3
    - opencv [win or linux]
    - opencv!=4.1.2 [osx]
    - matplotlib
    - vtk
    - pywin32 [win]
    - nose
    - coverage
    - sphinx
test:
  imports:
    - openalea.phenomenal
    - openalea.phenomenal.calibration
    - openalea.phenomenal.data
    - openalea.phenomenal.display
    - openalea.phenomenal.image
    - openalea.phenomenal.mesh
    - openalea.phenomenal.multi_view_reconstruction
    - openalea.phenomenal.object
    - openalea.phenomenal.segmentation
  requires:
    - pytest
  source_files:
    - test/test_calibration/**
    - test/test_image/**
    - test/test_mesh/**
    - test/test_multi_view_reconstruction/**
    - test/test_object/**
    - test/test_segmentation/**
  commands:
    - pytest

about:
  home: https://github.com/openalea/phenomenal
  license: Cecill-C License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - artzet-s
    - pradal
