package:
  name: openalea.phenomenal
  version: "1.7.1"

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  string: phenomenal
  script:
    - {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
    

  host:
    - python
    - setuptools
    - cython    
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - networkx<=2.3
    - opencv [win or linux]
    - opencv!=4.1.2 [osx]
    - matplotlib
    - vtk
    - pywin32 [win]

test:
  imports:
    - openalea.phenomenal
    - openalea.phenomenal.calibration
    - openalea.phenomenal.data
    - openalea.phenomenal.display
    - openalea.phenomenal.image
    - openalea.phenomenal.mesh
    - openalea.phenomenal.multi_view_reconstruction
    - openalea.phenomenal.object
    - openalea.phenomenal.segmentation
  requires:
    - pytest
  source_files:
    - test/data/**
    - test/test_calibration/**
    - test/test_image/**
    - test/test_mesh/**
    - test/test_multi_view_reconstruction/**
    - test/test_object/**
    - test/test_segmentation/**
  commands:
    - pytest

about:
  home: https://github.com/openalea/phenomenal
  license: Cecill-C License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - artzet-s
    - pradal
