{% set pyproject = load_file_data('pyproject.toml') %}
{% set description = pyproject.get('project').get('description') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}

{% set major = load_file_regex(
  load_file="src/openalea/phenomenal/version.py",
  regex_pattern='major = (.+)') %}
{% set minor = load_file_regex(
  load_file="src/openalea/phenomenal/version.py",
  regex_pattern='minor = (.+)') %}
{% set post = load_file_regex(
  load_file="src/openalea/phenomenal/version.py",
  regex_pattern='post = (.+)') %}

{% set version = major[1]+'.'+minor[1]+'.'+post[1] %}


package:
  name: openalea.phenomenal
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  string: phenomenal
  script: 
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - cython

  build:
    - {{ compiler('c') }} 
    - {{ compiler("cxx") }} 
    - python
    - setuptools
    - numpy
    - cython

  run:
    - python x.x
    - numpy x.x
    - cython
    - numba
    - scipy
    - scikit-image
    - scikit-learn
    - networkx
    - opencv [win or linux]
    - opencv >4.1.2 [osx]
    - matplotlib
    - vtk
    - skan
    - pywin32 [win]

test:
  imports:
    - openalea.phenomenal
    - openalea.phenomenal.calibration
    - openalea.phenomenal.data
    - openalea.phenomenal.display
    - openalea.phenomenal.image
    - openalea.phenomenal.mesh
    - openalea.phenomenal.multi_view_reconstruction
    - openalea.phenomenal.object
    - openalea.phenomenal.segmentation
    - openalea.phenomenal.tracking
  requires:
    - pytest
  source_files:
    - doc/examples/data/**
    - test/data/**
    - test/test_calibration/**
    - test/test_image/**
    - test/test_mesh/**
    - test/test_multi_view_reconstruction/**
    - test/test_object/**
    - test/test_tracking/**
    - test/test_segmentation/**
  commands:
    - pytest

about:
  home: {{ home }}
  summary: {{ description }}
  license: Cecill-C License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - artzet-s
    - pradal
