name: phenomenal
channels:
  - conda-forge
  - openalea

dependencies:
  - python
  - opencv
  - networkx=2.3
  - vtk
  - ipyvolume
  - pip:
      - scikit-learn
      - scikit-image
      - scipy
      - numba
      - numpy
      - cython
      - matplotlib
      - sphinx
      - sphinx_rtd_theme