name: phenomenal
channels:
  - conda-forge
  - openalea3

dependencies:
  - python
  - pydata-sphinx-theme
  - myst-parser
  - openalea.phenomenal
  - ipykernel
  - ipyvolume
  - ipython_genutils
  - pip
  - pip:
    - nbsphinx
