name: phenomenal
channels:
  - conda-forge
  - openalea

dependencies:
  - python
  - cython
  - opencv
  - numpy
  - numba
  - scipy
  - scikit-image
  - scikit-learn
  - networkx=2.3
  - matplotlib
  - vtk
  - sphinx
  - sphinx_rtd_theme
  - ipyvolume
