name: phenomenal
channels:
  - conda-forge
  - openalea

dependencies:
  - python
  - cython
  - opencv
  - numpy
  - numba
  - scipy
  - scikit-image
  - scikit-learn
  - networkx=2.3
  - vtk
  - ipyvolume
  - pip:
      - matplotlib
      - sphinx
      - sphinx_rtd_theme