name: phenomenal
channels:
  - conda-forge
  - openalea3

dependencies:
  - python
  - sphinx_rtd_theme
  - openalea.phenomenal
  - ipykernel
  - ipyvolume
  - ipython_genutils
  - pip
  - pip:
    - nbsphinx
