name: phenomenal
channels:
  - conda-forge
  - openalea
  - defaults
dependencies:
  - python
  - openalea.deploy
  - openalea.core
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - networkx <2.0
  - vtk
  - mayavi
  - wxpython
  - pyqt <5.0
  - scikit-image
  - opencv
  - nose
  - pyside
