package:
  name: openalea.phenomenal
  version: "1.0.0"

source:
  path: ../../

build:
  number: 0
  preserve_egg_dir: True
  string: phenomenal
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
    - pywin32 [win]
  run:
    - python
    - openalea.deploy
    - openalea.core
    - numpy
    - scikit-learn
    - scipy
    - matplotlib
    - networkx
    - vtk
    - scikit-image
    - opencv
    - pywin32 [win]
    - nose
    - coverage

test:
  imports:
    - openalea.phenomenal

  script: nosetests test

about:
  home: https://gitlab.inria.fr/phenome/phenomenal
  license: Cecill-C License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - artzet-s
